/** Preview spreadsheet rows — shown before Fiber returns live leads. */
export type MockLeadRow = {
  id: string;
  personName: string;
  role: string;
  companyName: string;
  locality: string;
  recentActivity: string;
  painSignal: string;
};

export const DEFAULT_ICP =
  "VPs of Sales and CFOs at unicorn SaaS startups in the United States";

export const MOCK_LEADS: MockLeadRow[] = [
  {
    id: "mock-1",
    personName: "Claire Hughes Johnson",
    role: "COO",
    companyName: "Stripe",
    locality: "San Francisco, CA",
    recentActivity: "Spoke at SaaStr on enterprise billing expansion",
    painSignal: "Multi-product GTM alignment",
  },
  {
    id: "mock-2",
    personName: "Elena Gomez",
    role: "CFO",
    companyName: "Stripe",
    locality: "South San Francisco, CA",
    recentActivity: "Posted on efficient growth at scale",
    painSignal: "CAC payback visibility",
  },
  {
    id: "mock-3",
    personName: "Dylan Field",
    role: "CEO & Co-founder",
    companyName: "Figma",
    locality: "San Francisco, CA",
    recentActivity: "Config keynote on design-dev handoff",
    painSignal: "Enterprise seat expansion",
  },
  {
    id: "mock-4",
    personName: "Ivan Zhao",
    role: "CEO & Co-founder",
    companyName: "Notion",
    locality: "San Francisco, CA",
    recentActivity: "AI workspace launch blog post",
    painSignal: "Team-wide adoption friction",
  },
  {
    id: "mock-5",
    personName: "Melanie Perkins",
    role: "CEO & Co-founder",
    companyName: "Canva",
    locality: "Sydney, Australia",
    recentActivity: "Enterprise brand governance rollout",
    painSignal: "Procurement cycle length",
  },
  {
    id: "mock-6",
    personName: "Apoorva Mehta",
    role: "Founder",
    companyName: "Instacart",
    locality: "San Francisco, CA",
    recentActivity: "Retail media network expansion news",
    painSignal: "Retailer partner churn",
  },
  {
    id: "mock-7",
    personName: "Chris Clark",
    role: "CFO",
    companyName: "Databricks",
    locality: "San Francisco, CA",
    recentActivity: "Data + AI summit investor day",
    painSignal: "Consumption revenue forecasting",
  },
  {
    id: "mock-8",
    personName: "Ali Ghodsi",
    role: "CEO & Co-founder",
    companyName: "Databricks",
    locality: "San Francisco, CA",
    recentActivity: "Lakehouse platform roadmap thread",
    painSignal: "Enterprise platform consolidation",
  },
  {
    id: "mock-9",
    personName: "Frank Slootman",
    role: "Executive Chairman",
    companyName: "Snowflake",
    locality: "Bozeman, MT",
    recentActivity: "Commentary on AI data cloud demand",
    painSignal: "Workload monetization",
  },
  {
    id: "mock-10",
    personName: "Mike Scarpelli",
    role: "CFO",
    companyName: "Snowflake",
    locality: "San Mateo, CA",
    recentActivity: "Q&A on net revenue retention trends",
    painSignal: "Expansion rep productivity",
  },
  {
    id: "mock-11",
    personName: "Eric Yuan",
    role: "Founder & CEO",
    companyName: "Zoom",
    locality: "San Jose, CA",
    recentActivity: "Contact center AI feature launch",
    painSignal: "Competitive displacement deals",
  },
  {
    id: "mock-12",
    personName: "Kelly Steckelberg",
    role: "CFO",
    companyName: "Zoom",
    locality: "San Jose, CA",
    recentActivity: "Investor update on enterprise mix shift",
    painSignal: "Pipeline conversion at scale",
  },
  {
    id: "mock-13",
    personName: "Todd McKinnon",
    role: "CEO & Co-founder",
    companyName: "Okta",
    locality: "San Francisco, CA",
    recentActivity: "Identity security summit keynote",
    painSignal: "Land-and-expand motion",
  },
  {
    id: "mock-14",
    personName: "Dave Schneider",
    role: "CFO",
    companyName: "Okta",
    locality: "San Francisco, CA",
    recentActivity: "Posted on efficient GTM investment",
    painSignal: "Sales cycle slippage",
  },
  {
    id: "mock-15",
    personName: "Henry Schuck",
    role: "CEO & Co-founder",
    companyName: "ZoomInfo",
    locality: "Vancouver, WA",
    recentActivity: "GTM data platform release notes",
    painSignal: "Data quality in outbound",
  },
  {
    id: "mock-16",
    personName: "Cameron McCord",
    role: "CFO",
    companyName: "ZoomInfo",
    locality: "Vancouver, WA",
    recentActivity: "Earnings call on platform upsell",
    painSignal: "Multi-threading enterprise deals",
  },
  {
    id: "mock-17",
    personName: "Patrick Collison",
    role: "CEO & Co-founder",
    companyName: "Stripe",
    locality: "San Francisco, CA",
    recentActivity: "Essay on progress in fintech infra",
    painSignal: "Global payments complexity",
  },
  {
    id: "mock-18",
    personName: "Arvind Jain",
    role: "CEO & Co-founder",
    companyName: "Glean",
    locality: "Palo Alto, CA",
    recentActivity: "Enterprise AI search case study",
    painSignal: "Security review bottlenecks",
  },
  {
    id: "mock-19",
    personName: "Karim Atiyeh",
    role: "CFO",
    companyName: "Ramp",
    locality: "New York, NY",
    recentActivity: "Spend management benchmark report",
    painSignal: "Finance-led expansion",
  },
  {
    id: "mock-20",
    personName: "Eric Glyman",
    role: "CEO & Co-founder",
    companyName: "Ramp",
    locality: "New York, NY",
    recentActivity: "LinkedIn post on corporate card adoption",
    painSignal: "Mid-market outbound efficiency",
  },
  {
    id: "mock-21",
    personName: "Maren Sullivan",
    role: "VP Sales",
    companyName: "Deel",
    locality: "San Francisco, CA",
    recentActivity: "Global payroll compliance webinar",
    painSignal: "International deal velocity",
  },
  {
    id: "mock-22",
    personName: "Alex Bouaziz",
    role: "CEO & Co-founder",
    companyName: "Deel",
    locality: "San Francisco, CA",
    recentActivity: "Remote work compliance expansion",
    painSignal: "Enterprise HRIS integrations",
  },
  {
    id: "mock-23",
    personName: "Sam Blond",
    role: "CRO",
    companyName: "Brex",
    locality: "San Francisco, CA",
    recentActivity: "Startup banking GTM playbook share",
    painSignal: "Founder-led sales handoff",
  },
  {
    id: "mock-24",
    personName: "Pedro Franceschi",
    role: "CEO & Co-founder",
    companyName: "Brex",
    locality: "San Francisco, CA",
    recentActivity: "Corporate card + treasury launch",
    painSignal: "Startup to enterprise transition",
  },
  {
    id: "mock-25",
    personName: "Christina Hall",
    role: "CFO",
    companyName: "Rippling",
    locality: "San Francisco, CA",
    recentActivity: "Unified workforce platform roadmap",
    painSignal: "Cross-sell attach rate",
  },
];
